// <auto-generated />
using Infra.Data.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PVHSAUDE.Infra.Data.Migrations;

[DbContext(typeof(Context))]
[Migration("20260918214500_CorrigirCodigosDependentes")]
partial class CorrigirCodigosDependentes
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The schema is unchanged by this data correction migration.
    }
}
