<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\PVHSAUDE.Application.csproj" />
    <ProjectReference Include="..\Infra.Helper\PVHSAUDE.Infra.Helper.csproj" />
  </ItemGroup>

</Project>
