<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.12" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.12" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\PVHSAUDE.Application.csproj" />
    <ProjectReference Include="..\Infra.Helper\PVHSAUDE.Infra.Helper.csproj" />
  </ItemGroup>

</Project>
